name: GitOps CI/CD
on:
  push:
    branches:
    - master
  
jobs:
  build:
    name: Build and Push the image
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: rajaninandu/node-helm-app:${{ github.sha }} , rajaninandu/node-helm-app:latest

  update:
    name: Update Helm Manifests
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Update Image Tag Values
      run: |
        chart_dir="chart"
        new_image_tag=${{ github.sha }}

        # Update the values.yaml file with the new image tag
        sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"
    
    - name: Commit the changes made
      run: | 
        git config --global user.name 'Rajani45'
        git config --global user.email 'rajaniindia1999@gamil.com'
        git commit -am "updating image tag"
        git push

    - name: Update kube config
      run: aws eks update-kubeconfig --region us-east-1 --name eks-WU

    - name: Deploy nodejs helm chart to EKS
      run: |
        helm upgrade node --install chart --namespace helm-deploy-eks
